### ISSUE TITLE
Bypass functions trick does not work

### ISSUE THREAD

**Issue by salcode** [dylanaraps/pure-bash-bible#1]
In the "Bypass shell aliases and functions", the trick of using a backslash does not work for functions `\` (though it does work for aliases).

This is on my Mac running

```
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)
Copyright (C) 2007 Free Software Foundation, Inc.
```

e.g.

```
$ logname
sal
$ function logname() { echo 'There is no logname, only Zuul.'; }
$ logname
There is no logname, only Zuul.
$ \logname
There is no logname, only Zuul.
```

Instead, you can use

```
$ $(which logname)
sal
```

or possibly with `-f` added

see https://salferrarello.com/command-line-which-wrong-result/#skipping-aliases-and-functions for more information.

**Comment by dylanaraps** [comment]
I’ll fix this, cheers. 👍

**Comment by dylanaraps** [comment]
Fixed

**Comment by salcode** [comment]
@dylanaraps 

Nice fix, I like the use of `command` instead of `$(which )` 👍
