### ISSUE TITLE
The name is a blasphemy, would you consider changing it?

### ISSUE THREAD

**Issue by DontUseGithub** [dylanaraps/pure-bash-bible#100]

**Comment by dylanaraps** [comment]
Words can have multiple meanings. :)
 
A secondary definition of "bible" is something along the lines of: "Any book accepted as authoritative or informative about a given subject". 

The word "bible" is actually from the Greek "τὰ βιβλία" or "Βιβλίο" which translate to "The books" or "Book" though this is considered an obsolete translation.

**Comment by cata0309** [comment]
![image](https://user-images.githubusercontent.com/35623921/76231066-5954c700-622d-11ea-8cb4-f0714bbd0ca7.png)
