### ISSUE TITLE
Regex [ Not an issue ]  [ Help needed ]

### ISSUE THREAD

**Issue by Akianonymus** [dylanaraps/pure-bash-bible#102]
Can we use bash regex to match on multiple lines ?

For ex, 
```
hello: one
hello: 2
Something: four
random: file
```

I want to extract just `hello` lines without grep, this may sound unnecessary, but just finding a way for the curious mind. :grinning: 

Edit: Obviously without running a loop

**Comment by chrisBosse** [comment]
I'm not sure this is the correct forum for this question or answer.

I'm not sure if this solution is correct, nor if there are any caveats, (line endings).

```regex
^(.*)(?=.*\n\1)
```

For whatever it may be worth. :grinning:
