### ISSUE TITLE
Deleted

### ISSUE THREAD

**Issue by ghost** [dylanaraps/pure-bash-bible#109]
[DEL]

**Comment by Nable80** [comment]
Why do you use ``printf`` and this complex redirection when simple ``cat /proc/sys/kernel/random/uuid`` is enough?

**Comment by dylanaraps** [comment]
This is Linux only.

**Comment by fable-cable** [comment]
Is give two, multiplatform and Linux but simplier, and less convoluted, impossible?

**Comment by fable-cable** [comment]
@Nable80 Because `cat` is not Pure Bash

**Comment by fable-cable** [comment]
Well, okay, screw it.
