### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by ghost** [dylanaraps/pure-bash-bible#131]
Hi everyone.

I want to help, but I want to know if this project is active. *Is this project active?*

**Comment by sroller** [comment]
It's a book. The book was published. As long as there's no update to the book there won't be much change.

**Comment by ghost** [comment]
H sroller.

> It's a book. The book was published. As long as there's no update to the book there won't be much change.

So, I want to translate in ptbr the book. *In this case, could I send a pull request with the translation of the bash book in ptbr? What do you think about the idea of translating the bash book to another language?*

**Comment by sroller** [comment]
Hi codehangen,

is ptbr  Brazilian Portuguese?

I'm not the author of the book. What I'd do if I were you :-) - I'd clone the project and do what I wanted to do. You can still send a merge request but why would you?

I'm not aware of the situation in Brazil with regard to language. I'm German and I found very little value in translating this type of book into the German language. People who are into shell programming are usually crazy and have enough command of English to understand this type of book.

**Comment by ghost** [comment]
Hi sroller.

> Hi codehangen,
> is ptbr Brazilian Portuguese?

yeah!

> I'm not the author of the book. What I'd do if I were you :-) - I'd clone the project and do what I wanted to do. You can still send a merge request but why would you?
> I'm not aware of the situation in Brazil with regard to language. I'm German and I found very little value in translating this type of book into the German language. People who are into shell programming are usually crazy and have enough command of English to understand this type of book.

thank you for feedback again here!
