### ISSUE TITLE
for loop

### ISSUE THREAD

**Issue by oceanMIH** [dylanaraps/pure-bash-bible#138]
for ((i=0;i<${#arr[@]};i++)); do
    printf '%s\n' "${arr[i]}"
done
=========================
the above code may be wrong if the array is not contiuous, or there are holes in the array
for example:
arr=(apple [3]=banana [6]=cherry)

**Comment by andry81** [comment]
You can recreate array:

```shell
arr2=("${arr[@]}")
```

**Comment by oceanMIH** [comment]
> You can recreate array:
> 
> ```shell
> arr2=("${arr[@]}")
> ```

yes, thanx
I think the following is better:
for i in ${!arr[@]}; do
printf '%s\n' "${arr[i]}"
done

**Comment by MegaV0lt** [comment]
Also should work without loop:

`printf '%s\n' "${arr[@]}"`
