### ISSUE TITLE
Random array element function

### ISSUE THREAD

**Issue by alphapapa** [dylanaraps/pure-bash-bible#18]
Hi,

Just noticed this repo and thought I would share this function that I came up with a few days ago:

```sh
function random_array_element {
    declare -n array="$1"  # namerefs are cool!  And it even works with the array being a local variable in another function!

    local length=${#array[@]}
    local index=$(( RANDOM % length))
    local choice=${array[$index]}

    echo "$choice"
}
```
Used like:
```sh
function choose_icon {
    # Return random icon.
    local icons=(
        /usr/share/icons/oxygen/22x22/emotes/face-embarrassed.png
        /usr/share/icons/oxygen/22x22/emotes/face-foot-in-mouth.png
        /usr/share/icons/oxygen/22x22/emotes/face-clown.png
        /usr/share/icons/oxygen/22x22/emotes/face-confused.png
        /usr/share/icons/oxygen/22x22/emotes/face-crying.png
        /usr/share/icons/oxygen/22x22/emotes/face-laugh.png
        /usr/share/icons/oxygen/22x22/emotes/face-laughing.png
        /usr/share/icons/oxygen/22x22/emotes/face-quiet.png
        /usr/share/icons/oxygen/22x22/emotes/face-raspberry.png
        /usr/share/icons/oxygen/22x22/emotes/face-sad.png
        /usr/share/icons/oxygen/22x22/emotes/face-sleeping.png
        /usr/share/icons/oxygen/22x22/emotes/face-smirk.png
        /usr/share/icons/oxygen/22x22/emotes/face-surprise.png
        /usr/share/icons/oxygen/22x22/emotes/face-uncertain.png
        /usr/share/icons/oxygen/22x22/emotes/face-wink.png
        /usr/share/icons/oxygen/22x22/emotes/face-worried.png
        /usr/share/icons/oxygen/22x22/emotes/face-yawn.png
        /usr/share/icons/oxygen/22x22/emotes/food-cake.png
        /usr/share/icons/oxygen/22x22/emotes/food-pizza.png
    )
    echo $(random_array_element icons)
}

choose_icon  # => "/usr/share/icons/oxygen/22x22/emotes/food-cake.png"
```

**Comment by dylanaraps** [comment]
Added to the README with some changes. Cheers :+1:

**Comment by dylanaraps** [comment]
I modified the function to match the others in the bible. `declare -n` doesn't work in `bash` 3 so I decided not to use it for the functions that deal with arrays.

These functions are just meant to be examples, they don't offer any error handling so I'm not bothered with overwriting global variables. In the future I'll most likely expand these functions so they're copy/paste-able into other scripts but for now they're just examples.

Thanks for the critique. :+1:

**Comment by alphapapa** [comment]
> These functions are just meant to be examples, they don't offer any error handling so I'm not bothered with overwriting global variables.

Seems a shame to set people up to make needless mistakes. 

> In the future I'll most likely expand these functions so they're copy/paste-able into other scripts but for now they're just examples.

Seems quite misleading for a "bible" to be comprised of examples which are not meant to be used as-is.  Might as well point people to `man bash`.
