### ISSUE TITLE
Do not recommend "$OSTYPE" instead of "uname"

### ISSUE THREAD

**Issue by ahmetb** [dylanaraps/pure-bash-bible#36]
1. $OSTYPE is inconsistent between the shells and uname:

   > ![image](https://user-images.githubusercontent.com/159209/44062021-9ab3e600-9f0f-11e8-9518-212e8c2c2674.png)

2. $OSTYPE contains a version suffix (see above) which requires a regexp to be stripped, whereas `uname` returns a plain string like `Darwin` or `Linux`.

**Comment by d3v1an7** [comment]
I think that's the point of pure bash though -- to avoid using `uname` :)

In the example provided, you can see how it's used with lossy matching, which should fit most use cases: https://github.com/dylanaraps/pure-bash-bible/blob/master/README.md#simpler-case-statement-to-set-variable

**Comment by gdzien** [comment]
IMHO this is BASH bible, so how other shells treat those things should not be a concern here.
Uname is binary, so it's not a BASH thing - therefore no place for that in "PURE BASH".
