### ISSUE TITLE
Caveat for 'split a string on a delimiter'

### ISSUE THREAD

**Issue by andres-rojas** [dylanaraps/pure-bash-bible#38]
https://github.com/dylanaraps/pure-bash-bible#split-a-string-on-a-delimiter

The `-a` option for `read` isn't available in every version of bash. At a minimum, it doesn't work on macOS's built-in bash (on macOS High Sierra, I'm running bash `3.2.57`).

This does work if I upgrade to bash 4+.

For what it's worth, I suspect there may be an alternative pure bash method to split a string into an array, but I haven't been able to come up with a perfectly generic function yet. Related: [this is a fun read](https://stackoverflow.com/a/45201229)

**Comment by halostatue** [comment]
The version of bash (`3.2.57`) that I have on my Mac does support `read -ra` (I’ve been depending on it pretty heavily in a build script that I’ve written).

**Comment by kingparra** [comment]
Why not just use `split() { local delim="$1"; local string "$2"; local result; readarray -d "$delim" result <<< "$string"; declare -p result; }`? It works with bash versions as early as 3.1, (tested by setting `shopt -s compat31`).
