### ISSUE TITLE
Webpage for Pure Bash Bible | Not an issue

### ISSUE THREAD

**Issue by meain** [dylanaraps/pure-bash-bible#44]
First of all, thanks for the great work.

I just wanted to let you know that I had built a UI around the content that is in the `README.md`.
I kinda thought it would be a great idea to have a searchable web interface around the content.

The project is https://github.com/meain/pbbui and I have hosted it currently on github at https://meain.github.io/pbbui/

**Comment by salmanulfarzy** [comment]
@meain This issue would be better noted if this had a better title reflecting the content.
