### ISSUE TITLE
Bash 5.0 breaks reverse_array in scripts

### ISSUE THREAD

**Issue by Crestwave** [dylanaraps/pure-bash-bible#57]
In Bash 5.0 scripts, `BASH_ARGV` also gets the current function's arguments when `extdebug` is enabled for the first time, so `reverse_array`'s results are printed twice. Relevant section of the [changelog](https://lists.gnu.org/archive/html/bug-bash/2019-01/msg00063.html):

>The shell doesn't automatically set BASH_ARGC and BASH_ARGV at startup unless it's in debugging mode, as the documentation has always said, but will dynamically create them if a script references them at the top level without having enabled debugging mode.

Compatibility with the old version is available with the `compat44` shell option.

**Comment by amno1** [comment]
reverse_array works just fine. It is just test (test_reverse_array ()) that is broken. 

Simple fix (as noted in your post):
```
test_reverse_array() {
    shopt -s compat44
    read -d "" -a result < <(reverse_array 1 2 3 4 5)
    assert_equals "${result[*]}" "5 4 3 2 1"
    shopt -u compat44
}
```

**Comment by dylanaraps** [comment]
You'll need to check the version of bash before setting `compat44` as it'll file in older versions.

**Comment by amno1** [comment]
Om dess:-)



Skickat från min Samsung Galaxy-smartphone.


-------- Originalmeddelande --------
Från: black <notifications@github.com>
Datum: 2019-02-05 07:08 (GMT+01:00)
Till: dylanaraps/pure-bash-bible <pure-bash-bible@noreply.github.com>
Kopia: amno1 <arthur.miller@live.com>, Comment <comment@noreply.github.com>
Ämne: Re: [dylanaraps/pure-bash-bible] Bash 5.0 breaks reverse_array in scripts (#57)


You'll need to check the version of bash before setting compat44 as it'll file in older versions.

**Comment by dylanaraps** [comment]
I'm looking into other methods of reversing an array, in the meantime I've added a note to the README.
