### ISSUE TITLE
realpath (and friends) in pure bash

### ISSUE THREAD

**Issue by pawamoy** [dylanaraps/pure-bash-bible#61]
When I saw your repo I immediately thought of this project: https://github.com/bashup/realpaths

This is up to you whether to include it in the README, of course.

Tagging @pjeby, the author :wink:

**Comment by pjeby** [comment]
Possibly worth noting is that the dirname and basename recipes given here aren't actually replacements for the `dirname` and `basename` commands.   The real `dirname` command doesn't include a trailing `/`, and it returns `.` for a plain name, e.g. the real `dirname foo` returns `.`, but the emulation here doesn't.  Similarly, the real `basename` command will strip multiple trailing slashes, but the emulation doesn't.

It might be worth adapting the emulations of dirname and basename  from realpaths, as they're still one-liners of pure bash, but are tested to be exact equivalents to the original commands, across quite a few scenarios that the emulations here aren't valid for.

**Comment by dylanaraps** [comment]
@pjeby, both `basename` and `dirname` in the bible match their external utilities 1:1 now. If you can reproduce cases in which they don't, I'd love to know.

**Comment by pjeby** [comment]
They don't handle multiple trailing slashes correctly.  Try strings like:

* `abc//`
* `//xyz/..//abc//`

etc.  There might be other problems, I'm not sure.  It's hard to do it right without using regular expression matching.

If you want to programmatically generate test cases, check out [this bit](https://github.com/bashup/realpaths/blob/master/specs/Paths.cram.md#dirname-and-basename) of bashup/realpath's test suite: just a few lines that generate around 700 different test paths to compare the function vs. the real thing.

**Comment by pawamoy** [comment]
Closing, feel free to reopen.
