### ISSUE TITLE
Not showing up on trending?

### ISSUE THREAD

**Issue by dylanaraps** [dylanaraps/pure-bash-bible#63]
This repository has received 700~ stars in the last 1-2 weeks and yet it is no where to be found on GitHub's trending page. I don't know if this is somehow related to the large influx of Chinese users who have recently found this repository. 

Can anyone else confirm or reproduce what I am seeing?

Source for prior star count (Wayback machine, see star count in "inspect element"):

![current](https://user-images.githubusercontent.com/6799467/59148308-f0c38a00-8a0f-11e9-8fc9-5ca0a59c9178.jpg)

**Comment by dylanaraps** [comment]
The repository now appears on trending for all three categories (day, week and month). If this was an error I thank whoever fixed it. Keeping this issue open for a few days.

**Comment by benjyfeen** [comment]
Just noted that I received a Trending email directing me to this repo. Guessing all is well now.
