### ISSUE TITLE
Feature request: Create integration with Gitbook?

### ISSUE THREAD

**Issue by securisec** [dylanaraps/pure-bash-bible#86]
It would be awesome to see this in a gitbook format. WIth the existing travis integration, it should be pretty easy to do so. Makes the doc nice and searchable then.

**Comment by dylanaraps** [comment]
If you'd like the book ready and automatically up-to-date in a different format, buy it! 

If you for some reason are unable to do so, that's fine too! As it's written in markdown it's easy to convert it to a myriad of formats through `pandoc` and other open source tools. :)
